
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = pepdefaultf.c pepmonf.c pepsetupf.c pepsolvef.c pepoptsf.c pepbasicf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcpep
LOCDIR   = src/pep/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
