
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = 
SOURCEF  =
SOURCEH  = slepcnep.h90 slepcbv.h90 slepcst.h90 slepcpep.h90 slepcmfn.h90 slepcds.h90 slepceps.h90 slepcfn.h90 slepcsys.h90 slepcsvd.h90 slepcrg.h90
DIRS     =
LIBBASE   = libslepcsys
LOCDIR    = include/slepc/finclude/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
