
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = epsviewf.c epsoptsf.c epsmonf.c epsdefaultf.c epssetupf.c epssolvef.c epsbasicf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepceps
LOCDIR   = src/eps/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
