
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = epsdefaultf.c epssetupf.c epsoptsf.c epsmonf.c epsbasicf.c epssolvef.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepceps
LOCDIR   = src/eps/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
