
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = svdviewf.c svdbasicf.c svdmonf.c svdsolvef.c svdoptsf.c svdsetupf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcsvd
LOCDIR   = src/svd/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
