
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mfnbasicf.c mfnsolvef.c mfnoptsf.c mfnsetupf.c mfnmonf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcmfn
LOCDIR   = src/mfn/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
