
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mfnsetupf.c mfnsolvef.c mfnbasicf.c mfnoptsf.c mfnmonf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcmfn
LOCDIR   = src/mfn/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
