
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nepoptsf.c nepmonf.c nepsolvef.c nepbasicf.c nepsetupf.c nepdefaultf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcnep
LOCDIR   = src/nep/interface/ftn-auto/
include ${SLEPC_DIR}/conf/slepc_common
