
#requiresdefine   'PETSC_HAVE_FORTRAN'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = nepviewf.c nepsetupf.c nepdefaultf.c nepsolvef.c nepoptsf.c nepmonf.c nepbasicf.c
SOURCEF  =
SOURCEH  = 
DIRS     =
LIBBASE  = libslepcnep
LOCDIR   = src/nep/interface/ftn-auto/
include ${SLEPC_DIR}/lib/slepc/conf/slepc_common
